name: CI

on:
  push:
  pull_request:
  schedule:
  - cron:  '0 0 1 * *' # at 00:00 on the 1st of every month

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        ruby: [ 3.1, 3.2, 3.3, ruby-head, jruby, truffleruby ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Install Ruby ${{ matrix.ruby }}, install and cache dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake

  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
    - run: gem build spinels-rack-ssl-enforcer
    - run: gem install *.gem
