name: CI

on:
  push:
  pull_request:
  schedule:
  - cron:  '0 0 1 * *' # at 00:00 on the 1st of every month

jobs:
  test:
    name: ruby ${{ matrix.ruby }}, rack ${{ matrix.rack }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.1
          - 3.2
          - 3.3
          - ruby-head
          - jruby
          - truffleruby
        rack:
          - ~>3.1.0
        include:
          - { ruby: 3.1, rack: ~>3.0.0 }
          - { ruby: 3.3, rack: head }
    env:
      rack: ${{ matrix.rack }}
    steps:
    - uses: actions/checkout@v4

    - name: Install Ruby ${{ matrix.ruby }}, install and cache dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: List installed dependencies
      run: bundle show

    - name: Run tests
      run: bundle exec rake

  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
    - run: gem build spinels-rack-ssl-enforcer
    - run: gem install *.gem
